# frozen_string_literal: true

source "https://rubygems.org"
ruby "2.4.2"  # ruby version, change for the one you use
#git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem 'whenever'
gem 'date'
gem 'nokogiri'
#gem 'open-uri'
gem 'mechanize'
gem 'csv'